@startuml SEQ04_changePassword
    title: Đổi mật khẩu

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor "User" as user
    boundary "User Interface\nClass" as ui
    control "User Controller\nClass" as ctr
    control "User Service\nClass" as sv
    entity "User \nClass" as ent

    autonumber

    user -> ui: Truy cập màn hình thông tin \n cá nhân và chọn đổi mật khẩu
    ui ++
    ui --> user: Hiện màn hình đổi mật khẩu tài khoản
    user -> ui: Điền mật khẩu cũ, mật khẩu mới, xác\n nhận lại mật khẩu mới và nhấn gửi
    ui -> ctr: Gửi thông tin đã nhập và \n yêu cầu đổi lại mật khẩu
    ctr ++
    ctr -> sv: Gửi thông tin đã nhập và \n yêu cầu đổi lại mật khẩu
    sv ++
    sv -> ent: Lưu mật khẩu mới vào CSDL
    ent ++
    
    ent --> sv: Trả về thông báo mật khẩu \n mới đã được cập nhật
    ent --
    sv --> ctr: Trả về thông báo mật khẩu \n mới đã được cập nhật
    sv --
    ctr --> ui: Trả về thông báo mật khẩu \n mới đã được cập nhật
    ctr--
    ui --> user: Hiển thị thông báo mật khẩu mới đã \n được cập nhật và chuyển hướng đến \n trang chính
    ui --
@enduml