@startuml SEQ03_forgetPassword
    title: Quên mật khẩu

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor "User" as user
    boundary "Forgot Password Interface\nClass" as ui
    control "Authentication Controller\nClass" as ctr
    control "Authentication Service\nClass" as sv
    entity "User \nClass" as ent

    user -> ui: Truy cập màn hình quên mật khẩu
    ui ++
    ui --> user: Hiện màn hình quên mật khẩu
    user -> ui: Điền thông tin gmail/số điện thoại\nvà nhấn gửi
    ui -> ctr: Gửi thông tin đã nhập và \n yêu cầu lấy lại mật khẩu
    ctr ++
    ctr -> sv: Gửi thông tin đã nhập và \n yêu cầu lấy lại mật khẩu
    sv ++
    sv -> ent: Kiểm tra thông tin email/sđt đã nhập
    ent ++
    
    alt Thông tin email/số điện thoại không \n hợp lệ (không tồn tại trong hệ thống)
        ent --> sv: Trả về thông báo email/số \n điện thoạikhông tồn tại
        sv --> ctr: Trả về thông báo email/số \n điện thoại không tồn tại
        ctr --> ui: Trả về thông báo email/số \n điện thoại không tồn tại
        ui --> user: Hiển thị thông báo email/số điện thoại không tồn tại
    else Thông tin email/số điện thoại hợp lệ
        ent --> sv: Trả về thông tin email/số điện thoại hợp lệ
        sv --> ctr: Trả về thông báo email/số điện thoại hợp lệ
        ctr --> ui: Trả về thông báo email/số điện thoại hợp lệ
        ui --> user: Hiển thị màn hình nhập mật khẩu mới
        user -> ui: Nhập mật khẩu mới và \n xác nhận mật khẩu mới
        ui -> ctr: Gửi thông tin mật khẩu mới \n và xác nhận mật khẩu mới
        ctr -> sv: Gửi thông tin mật khẩu mới \n và xác nhận mật khẩu mới

        alt Mật khẩu mới không hợp lệ (sai định dạng)
            sv --> ctr: Trả về thông báo mật khẩu mới không hợp lệ
            ctr --> ui: Trả về thông báo mật khẩu mới không hợp lệ
            ui --> user: Hiển thị thông báo mật khẩu mới không hợp lệ
        else Mật khẩu mới hợp lệ (đúng điều kiện)
            sv -> ent: Gửi thông tin mật khẩu mới\n và lưu mật khẩu mới vào CSDL
            ent --> sv: Trả về thông báo mật khẩu \n mới đã được cập nhật
            ent --
            sv --> ctr: Trả về thông báo mật khẩu \n mới đã được cập nhật
            sv --
            ctr --> ui: Trả về thông báo mật khẩu \n mới đã được cập nhật
            ctr--
            ui --> user: Hiển thị thông báo mật khẩu mới đã \n được cập nhật và chuyển hướng đến \n trang đăng nhập
            ui --
        end

    end
@enduml