@startuml SEQ06_Logout

    title: Đăng xuất

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor "User" as user
    boundary "Log out Interface\nClass" as ui
    control "Authentication Controller\nClass" as ctr
    control "Authentication Service\nClass" as sv
    entity "User \nClass" as ent

    user -> ui: Truy cập vào màn hình \n "Cá nhân"
    ui ++
    ui --> user: Hiện thông báo xác nhận đăng xuất
    alt Người dùng không xác \n nhận đăng xuất
        user -> ui: Nhấn hủy bỏ
        ui --> user: Đóng thông báo
    else Người dùng xác nhận đăng xuất
        ui -> ctr: Gửi yêu cầu đăng xuất
        ctr ++
        ctr -> sv: Gửi yêu cầu đăng xuất
        sv ++
        sv -> ent: Xóa thông tin đăng nhập (token)
        ent ++
        ent --> sv: Trả về thông báo đăng xuất thành công
        ent --
        sv --> ctr: Trả về thông báo đăng xuất thành công
        sv --
        ctr --> ui: Trả về thông báo đăng xuất thành công
        ctr--
        ui --> user: Hiển thị thông báo đăng xuất thành công\n và chuyển hướng đến trang đăng nhập
    end
@enduml