@startuml SEQ05_DeleteAccount

    title: Xóa tài khoản

    skin rose
    scale 2
    hide footbox

    autonumber

    actor "User" as user
    boundary ": User Interface\nClass" as ui
    control ": User Controller\nClass" as ctr
    control ": User Service\nClass" as userSv
    control ": Album \nService" as albumSv
    control ": Trip \nService" as tripSv
    control ": Trip place \nService" as tripPlaceSv
    entity ": Album \nClass" as albumEnt
    entity ": Trip \nClass" as tripEnt
    entity ": Trip place \nClass" as tripPlaceEnt
    entity ": User \nClass" as userEnt

    user ++
    user -> ui: Truy cập vào màn hình \n "Hồ sơ" và chọn xóa tài khoản
    ui ++
    ui -> user: Hiện thông báo xác nhận\n xóa tài khoản
    alt Người dùng không xác \n nhận xóa tài khoản
        user --> ui: Nhấn hủy bỏ
        ui -> user: Hủy thao tác
    else Người dùng xác nhận xóa tài khoản

        autonumber 3
        
        user --> ui: Nhấn xác nhận xóa tài khoản
        ui -> ctr: Gửi yêu cầu xóa tài khoản
        ctr ++
        ctr -> userSv: Gửi yêu cầu xóa tài khoản
        userSv ++
        userSv -> albumSv: Gửi yêu cầu xóa album \n của tài khoản
        albumSv ++
        albumSv -> albumEnt: Xóa album của tài khoản
        albumEnt ++
        albumEnt --> albumSv: Trả về thông báo xóa album thành công
        albumEnt --
        albumSv --> userSv: Trả về thông báo\n xóa album thành công
        albumSv --
        userSv -> tripSv: Gửi yêu cầu xóa chuyến đi \n của tài khoản
        tripSv ++
        tripSv -> tripPlaceSv: Gửi yêu cầu xóa địa điểm \n của chuyến đi
        tripPlaceSv ++
        tripPlaceSv -> tripPlaceEnt: Xóa địa điểm của chuyến đi
        tripPlaceEnt ++
        tripPlaceEnt --> tripPlaceSv: Trả về thông báo xóa\n địa điểm thành công
        tripPlaceEnt --
        tripPlaceSv -> tripEnt: Xóa chuyến đi của tài khoản
        tripEnt ++
        tripEnt --> tripPlaceSv: Trả về thông báo xóa\n chuyến đi thành công
        tripEnt --
        tripPlaceSv --> tripSv: Trả về thông báo xóa\n chuyến đi thành công
        tripPlaceSv --
        tripSv --> userSv: Trả về thông báo xóa\n chuyến đi thành công
        tripSv --
        userSv -> userEnt: Xóa tài khoản
        userEnt ++
        userEnt --> userSv: Trả về thông báo xóa\n tài khoản thành công
        userEnt --
        userSv --> ctr: Trả về thông báo xóa\n tài khoản thành công
        userSv --
        ctr --> ui: Trả về thông báo xóa\n tài khoản thành công
        ctr--
        ui --> user: Hiển thị thông báo xóa tài\n khoản thành công và chuyển\n hướng đến trang đăng nhập
    end
    user --
@enduml