@startuml SEQ01_DangNhap
    title: Đăng nhập

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor "User/Admin" as user
    boundary "User Interface\nClass" as ui
    control "User Controller\nClass" as ctr
    control "User Service\nClass" as sv
    entity "User \nClass" as ent

    autonumber

    user -> ui: Truy cập trang đăng nhập
    ui ++
    ui --> user: Hiện màn hình đăng nhập tài khoản
    user -> ui: Điền thông tin tài khoản\nvà nhấn đăng nhập
    ui -> ctr: Gửi yêu cầu và thông tin\nđăng nhập
    ctr ++
    ctr -> sv: Gửi yêu cầu và thông tin\nđăng nhập
    sv ++
    sv -> sv: Kiểm tra thông tin đăng nhập
    
    alt Thông tin đăng nhập không hợp lệ
        
        autonumber 5
        sv --> ctr: Trả về thông báo lỗi
        ctr --> ui: Trả về thông báo lỗi
        ui --> user: Hiển thị thông báo lỗi
    
    else Thông tin đăng nhập hợp lệ
        
        autonumber 5

        sv -> ent: Gửi thông tin đăng nhập
        ent ++

        alt Tài khoản không hợp lệ

            autonumber 6

            ent --> sv: Trả về thông báo tài khoản\nkhông hợp lệ
            sv --> ctr: Trả về thông báo tài khoản\nkhông hợp lệ
            ctr --> ui: Trả về thông báo tài khoản\nkhông hợp lệ
            ui --> user: Hiển thị thông báo tài khoản\nkhông hợp lệ
        
        else Tài khoản hợp lệ
            
            autonumber 6

            ent --> sv: Trả về thông tin tài khoản hợp lệ
            ent --
            sv --> ctr: Trả về thông tin tài khoản hợp lệ
            sv --
            ctr --> ui: Trả về thông tin tài khoản hợp lệ
            ctr --
            ui --> user: Hiển thị thông báo đăng nhập thành công\nvà chuyển hướng đến trang chính
            ui --
        end
    end
@enduml