@startuml SEQ07_MapInteract
    title: Tương tác bản đồ

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor "User" as user
    boundary "User Interface\nClass" as ui
    control "Map Controller\nClass" as ctr
    control "Map Service\nClass" as mapSv
    control "Place Service\nClass" as placeSv
    entity "Place \nClass" as ent

    autonumber

    user -> ui: Truy cập vào ứng dụng \n(Mặc định người dùng có kết nối với internet)
    ui ++
    ui -> ctr: Gửi yêu cầu lấy dữ liệu bản đồ
    ctr ++
    ctr -> mapSv: Gửi yêu cầu lấy dữ liệu bản đồ
    mapSv ++
    mapSv -> mapSv: Lấy dữ liệu bản đồ từ \n API Google Map
    mapSv -> placeSv: Gửi yêu cầu lấy dữ \n liệu địa điểm du lịch
    placeSv ++
    placeSv -> ent: Lấy dữ liệu địa điểm du lịch
    ent ++
    ent --> placeSv: Trả về dữ liệu địa điểm du lịch
    ent --
    placeSv --> mapSv: Trả về dữ liệu địa điểm du lịch
    placeSv --
    mapSv --> ctr: Trả về dữ liệu bản đồ và \n dữ liệu địa điểm du lịch
    mapSv --
    ctr --> ui: Hiển thị bản đồ và dữ liệu \n địa điểm du lịch
    ctr --
    ui --> user: Hiện màn hình chính của \n ứng dụng
    ui --
    
@enduml