@startuml SEQ02_signUp
    title: Đăng ký

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor "User" as user
    boundary "User Interface\nClass" as ui
    control "User Controller\nClass" as ctr
    control "User Service\nClass" as sv
    entity "User \nClass" as ent

    autonumber

    user -> ui: Truy cập màn hình đăng ký
    ui ++
    ui --> user: Hiện màn hình đăng ký tài khoản
    user -> ui: Điền thông tin đăng ký\nvà nhấn đăng ký
    ui -> ctr: Gửi yêu cầu và thông tin\nđăng ký
    ctr++
    ctr -> sv: Gửi yêu cầu và thông tin\nđăng ký
    sv++
    sv -> sv: Kiểm tra thông tin đăng ký
    
    alt Thông tin đăng ký không hợp lệ (sai định dạng)

        autonumber 5

        sv --> ctr: Trả về thông báo lỗi
        ctr --> ui: Trả về thông báo lỗi
        ui --> user: Hiển thị thông báo lỗi

    else Thông tin đăng ký hợp lệ

        autonumber 5

        sv -> ent: Lưu thông tin đăng ký
        ent ++

        alt Tài khoản không hợp lệ (đã tồn tại)
            ent --> sv: Trả về thông báo tài khoản\nđã tồn tại
            sv --> ctr: Trả về thông báo tài khoản\nđã tồn tại
            ctr --> ui: Trả về thông báo tài khoản\nđã tồn tại
            ui --> user: Hiển thị thông báo đăng ký\ntài khoản không thành công
        
        else Tài khoản hợp lệ

            autonumber 6

            ent --> sv: Trả về thông tin tài khoản hợp lệ
            ent -- 
            sv --> ctr: Trả về thông tin tài khoản hợp lệ
            sv --
            ctr --> ui: Trả về thông tin tài khoản hợp lệ
            ctr -- 
            ui --> user: Hiển thị thông báo đăng ký thành công\nvà chuyển hướng đến trang chính
            ui --
        end
    end
@enduml