@startuml SEQ07_CheckInPlace
    title: Check-in địa điểm du lịch

    skin rose
    scale 2
    hide footbox

    actor "User" as user
    boundary ": User Interface\nClass" as ui
    control ": User Controller\nClass" as ctr
    control ": User Service\nClass" as sv
    entity ": User \nClass" as ent

    autonumber

    user ++
    user -> ui: Người dùng ấn vào thông báo check-in\n của ứng dụng khi tới địa điểm du lịch
    ui ++
    ui --> user: Hiện thông báo xác nhận check-in
    user -> ui: Nhấn xác nhận check-in
    ui -> ctr: Gửi yêu cầu check-in
    ctr ++
    ctr -> sv: Gửi yêu cầu check-in
    sv ++
    sv -> ent: Lưu thông tin check-in vào CSDL
    ent ++
    ent --> sv: Trả về thông báo check-in thành công
    ent --
    sv --> ctr: Trả về thông báo check-in thành công
    sv --
    ctr --> ui: Trả về thông báo check-in thành công
    ctr--
    ui --> user: Hiển thị thông báo check-in thành công\n và chuyển hướng đến trang chính
    ui --
    user --

@enduml