@startuml AddFavoritePlace

    title Thêm địa điểm du lịch vào danh sách yêu thích

    skin rose
    scale 2
    hide footbox

    actor User as user
    boundary ": User Interface\nClass" as ui
    control ": User Controller\nClass" as uc
    control ": User Service\nClass" as us
    entity ": User\nClass" as u

    autonumber
    user++
    user -> ui++ : Ấn vào nút "Thêm vào \n danh sách yêu thích"
    ui -> user : Gửi yêu cầu xác nhận hành động
    alt Người dùng không xác nhận
        user --> ui : Ấn nút "Hủy"
        ui --> user : Hủy thao tác
    else Người dùng xác nhận
        autonumber 3
        user --> ui: Ấn nút "Xác nhận"
        ui -> uc++ : Gửi yêu cầu thêm vào \n danh sách yêu thích
        uc -> us++ : Điều hướng đến\nservice tương ứng
        us -> u++ : Thêm địa điểm vào danh sách yêu thích
        u --> us : Trả về kết quả
        u --
        us --> uc : Trả về kết quả
        us --
        uc --> ui : Trả về kết quả
        uc --
        ui --> user : Hiển thị thông báo thêm thành công
        ui --
    end
    user--

@enduml