@startuml RatingPlace

    title Đánh giá địa điểm du lịch

    skin rose
    scale 2
    hide footbox

    actor User as user
    boundary ": User Interface\nClass" as ui
    control ": Place Controller\nClass" as pc
    control ": Place Service\nClass" as ps
    entity ": Place\nClass" as p

    autonumber

    user++
    user -> ui++ : Ấn vào xem thông tin \n địa điểm đã check-in
    ui --> user : Hiển thị thông tin chi tiết \n của địa điểm
    user -> ui : Người dùng cho điểm \n và để lại bình luận
    ui -> pc++ : Gửi yêu cầu đánh giá \n địa điểm
    pc -> ps++ : Điều hướng đến\nservice tương ứng
    ps -> p++ : Lưu thông tin đánh giá, bình luận \n vào cơ sở dữ liệu
    p --> ps : Trả về kết quả
    p --
    ps --> pc : Trả về kết quả
    ps --
    pc --> ui : Trả về kết quả
    pc --
    ui --> user : Hiển thị thông báo đánh giá thành công
    user--

@enduml