@startuml SEQ10_XemDanhSachDiaDiemDuLich

title Xem danh sách địa điểm du lịch

skin rose
scale 2
skinparam sequenceMessageAlign center
hide footbox

actor "User/Admin" as user
boundary ": User Interface\nClass" as ui
control ": Place Controller\nClass" as pc
control ": Place Service\nClass" as ps
entity ": Place\nClass" as p

autonumber
user++
user -> ui++ : Ấn vào mục "Địa điểm du lịch"\nở giao diện hồ sơ người dùng
ui -> pc++ : Gửi yêu cầu lấy danh sách\nđịa điểm du lịch
pc -> ps++ : Điều hướng đến\nservice tương ứng
ps -> p++ : Lấy danh sách\nđịa điểm du lịch
p --> ps-- : Trả về danh sách\nđịa điểm du lịch
ps --> pc-- : Trả về danh sách\nđịa điểm du lịch
pc --> ui-- : Trả về danh sách\nđịa điểm du lịch
ui --> user-- : Hiển thị danh sách\nđịa điểm du lịch
user --

@enduml