@startuml AddFavoritePlace

    title Thêm địa điểm du lịch vào danh sách yêu thích

    skin rose
    scale 2
    hide footbox

    actor User as user
    boundary ": User Interface\nClass" as ui
    control ": User Controller\nClass" as uc
    control ": User Service\nClass" as us
    entity ": User\nClass" as u

    autonumber
    user++
    user -> ui++ : Ấn vào biểu tượng\n trái tim trắng
    ui -> uc++ : Gửi yêu cầu thêm vào \n danh sách yêu thích
    uc -> us++ : Điều hướng đến\nservice tương ứng
    us -> u++ : Thêm địa điểm vào\n danh sách yêu thích
    u --> us : Trả về kết quả
    u --
    us --> uc : Trả về kết quả
    us --
    uc --> ui : Trả về kết quả
    uc --
    ui --> user : Hiển thị thông báo\n thêm thành công
    ui --
    user--

@enduml