@startuml SEQ15_TimKiemDiaDiemDuLich

    title Tìm kiếm địa điểm du lịch

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor User as user
    boundary ": User Interface\nClass" as ui
    control ": Place Controller\nClass" as pc
    control ": Place Service\nClass" as ps
    entity ": Place\nClass" as p

    autonumber
    user++
    user -> ui++ : Nhập thông tin tìm kiếm\nvà ấn "Tìm kiếm"
    ui -> pc++ : Gửi yêu cầu tìm kiếm\nđịa điểm du lịch
    pc -> ps++ : Điều hướng đến\nservice tương ứng
    ps -> p++ : Tìm kiếm địa điểm du lịch
    p --> ps-- : Trả về danh sách địa điểm du lịch
    ps --> pc-- : Trả về danh sách địa điểm du lịch
    pc --> ui-- : Trả về danh sách địa điểm du lịch
    ui --> user-- : Hiển thị danh sách địa điểm du lịch

@enduml