@startuml SEQ14_XoaDiaDiemDuLich

    title Xóa địa điểm du lịch

    skin rose
    scale 2
    skinparam sequenceMessageAlign center
    hide footbox

    actor Admin as ad
    boundary ": User Interface\nClass" as ui
    control ": Trip Controller\nClass" as tc
    control ": Trip Service\nClass" as ts
    entity ": Trip\nClass" as t

    autonumber
    ad++
    ad -> ui++ : Ấn vào nút xóa ở màn hình\nthông tin địa điểm du lịch
    ui -> ad : Yêu cầu quản trị viên xác nhận
    alt quản trị viên không xác nhận
        ad --> ui : Ấn "Hủy"
        ui --> ad : Hiển thị màn hình\nthông tin địa điểm du lịch
    else quản trị viên xác nhận
        autonumber 5
        ad --> ui : Xác nhận
        ui -> tc++ : Gửi yêu cầu xóa địa điểm du lịch
        tc -> ts++ : Điều hướng đến\nservice tương ứng
        ts -> t++ : Xóa địa điểm du lịch
        t --> ts-- : Trả về thông báo thành công
        ts --> tc-- : Trả về thông báo thành công
        tc --> ui-- : Trả về thông báo thành công
        ui --> ad-- : Hiển thị thông báo thành công
    end
    
@enduml