@startuml XemDanhSachDiaDiemUaThich

title Xem danh sách địa điểm ưa thích

skin rose
scale 2
hide footbox

actor User as user
boundary ": User Interface\nClass" as ui
control ": Place Controller\nClass" as pc
control ": Place Service\nClass" as ps
entity ": Place\nClass" as p

autonumber
user++
user -> ui++ : Ấn vào mục "Địa điểm ưa thích"\nở giao diện hồ sơ người dùng
ui -> pc++ : Gửi yêu cầu lấy danh sách\nđịa điểm ưa thích
pc -> ps++ : Điều hướng đến\nservice tương ứng
ps -> p++ : Lấy danh sách\nđịa điểm ưa thích
p --> ps-- : Trả về danh sách\nđịa điểm ưa thích
ps --> pc-- : Trả về danh sách\nđịa điểm ưa thích
pc --> ui-- : Trả về danh sách\nđịa điểm ưa thích
ui --> user-- : Hiển thị danh sách\nđịa điểm ưa thích
user --

@enduml