@startuml AddPlaces

    title Thêm địa điểm du lịch

    skin rose
    scale 2
    hide footbox

    actor "Admin" as ad
    boundary ": User Interface\nClass" as ui
    control ": Place Controller\nClass" as pc
    control ": Place Service\nClass" as ps
    entity ": Place\nClass" as p

    autonumber

    user ++
    ad -> ui : Ấn vào mục "Thêm địa điểm"\nở giao diện quản trị viên
    ui ++
    ui --> ad : Hiển thị giao diện\nthêm địa điểm
    ad -> ui : Điền thông tin địa điểm\nvà ấn nút "Thêm"
    ui --> ad : Hiển thị hộp thoại yêu cầu\nxác nhận thêm địa điểm

    alt Quản trị viên không xác nhận
        ad --> ui : Ấn nút "Hủy"
        ui -> ad : Hủy thao tác
    else Quản trị viên xác nhận
        autonumber 5
        ad --> ui : Ấn nút "Xác nhận"
        ui -> pc : Gửi thông tin địa điểm\nđến controller
        pc ++
        pc -> ps : Gửi thông tin địa điểm\nđến service
        ps ++
        ps -> ps : Kiểm tra thông tin địa điểm\nđã nhập
        alt Địa điểm đã tồn tại trong CSDL
            ps --> pc : Trả về thông báo\nđịa điểm đã tồn tại
            pc --> ui : Trả về thông báo\nđịa điểm đã tồn tại
            ui --> ad : Hiển thị thông báo\nđịa điểm đã tồn tại
        else Địa điểm chưa tồn tại trong CSDL

            autonumber 7

            ps -> p : Lưu thông tin địa điểm\nvào CSDL
            p++
            p --> ps : Trả về thông báo\nđịa điểm đã được thêm
            p --
            ps --> pc : Trả về thông báo\nđịa điểm đã được thêm
            ps --
            pc --> ui : Trả về thông báo\nđịa điểm đã được thêm
            pc --
            ui --> ad : Hiển thị thông báo\nđịa điểm đã được thêm
            ui --
        end
    end
    user --

@enduml
