@startuml SuaChuyenDi

title Sửa chuyến đi

skin rose
scale 2
hide footbox

actor User as user
boundary ": User Interface\nClass" as ui
control ": Trip Controller\nClass" as tc
control ": Trip Service\nClass" as ts
entity ": Trip\nClass" as t

autonumber
user++
user -> ui++ : Ấn vào nút "Sửa" ở màn hình\nthông tin chuyến đi
ui --> user : Hiển thị màn hình\nsửa thông tin chuyến đi
user -> ui : Nhập thông tin và ấn "Lưu"
ui -> user : Yêu cầu người dùng xác nhận
alt Người dùng không xác nhận
    user --> ui : Ấn "Hủy"
    ui --> user : Hiển thị màn hình\nthông tin chuyến đi
else Người dùng xác nhận
    autonumber 5
    user --> ui : Xác nhận
    ui -> tc++ : Gửi yêu cầu sửa\nthông tin chuyến đi
    tc -> ts++ : Điều hướng đến\nservice tương ứng
    ts -> ts : Kiểm tra thông tin\nchuyến đi
    alt Thông tin không hợp lệ
        ts --> tc : Trả về thông báo lỗi
        tc --> ui : Trả về thông báo lỗi
        ui --> user : Hiển thị thông báo lỗi
    else Thông tin hợp lệ
        autonumber 9
        ts -> t++ : Sửa thông tin chuyến đi
        t --> ts-- : Trả về thông báo thành công
        ts --> tc-- : Trả về thông báo thành công
        tc --> ui-- : Trả về thông báo thành công
        ui --> user-- : Hiển thị thông báo thành công
    end
end

