@startuml ClassConceptualDiagram

skin rose
scale 2

class Album {}


class User {
}

class Place {
}

class Feedback {
}

class Section {
}

class FavouritePlace {
}

class Trip {
}

class TripPlace {
}

class RefreshToken {
}

enum UserRole {
}

class PlaceCategory {
}

class Province {
}

class District {
}

class Ward {
}

class AdministrativeRegion {
}

class AdministrativeUnit {
}

class ProvinceDetail {
}

class Post {
}

class Comment {
}

class Like {
}

class CheckIn {
}

User -right- Trip
User -left- Album
User -up- FavouritePlace
User -down- RefreshToken
User -down- Post
User -down- Comment
User -up- CheckIn
User -down- Like
User -up- UserRole

' Album -left- AlbumImage
' Album -up- Place

Trip -right- TripPlace

Place -down- Feedback
Place -up- PlaceDetail
Place -up- PlaceCategory
' Place -up- PlaceImage
Place -down- FavouritePlace
Place -down- CheckIn
Place -down- TripPlace

PlaceDetail -right- Section


' Feedback -up- FeedbackImage
Feedback -right- User

Province -up- AdministrativeUnit
Province -up- AdministrativeRegion
Province -left- ProvinceDetail

District -up- AdministrativeUnit
District -left- Province

Ward -up- AdministrativeUnit
Ward -left- District

Post -down- Comment
' Post -up- Like
Post -up- Trip

' Comment -up- Like

Address -up- Province
Address -up- District
Address -up- Ward
Address -down- AddressTargetType

Image -up- ImageTargetType

Like -up- LikeTargetType

@enduml