@startuml ClassConceptualDiagram

skin rose
scale 2
hide circle

class Album {}

class AlbumImage {
}

class BaseUser {
}

class Admin {
}

class User {
}

class Place {
}

class PlaceImage {
}

class Feedback {
}

class FeedbackImage {
}

class Section {
}

class FavouritePlace {
}

class Trip {
}

class TripPlace {
}

class RefreshToken {
}

enum UserRole {
}

enum PlaceCategory {
}

class Province {
}

class District {
}

class Ward {
}

class Region {
}

class Unit {
}

class ProvinceDetail {
}




BaseUser <|-right- Admin
BaseUser <|-down- User
Place -left- Feedback
Feedback -down- FeedbackImage
User -down- Trip
User -left- FavouritePlace
Trip -left- TripPlace
User -right- Album
Album -down- AlbumImage
Place -up- Section
Place -down- PlaceImage

PlaceCategory -- Place

Province -- Unit
Province -- Region

District -- Unit
District -- Province

Ward -- Unit
Ward -- District

ProvinceDetail -- Province

Place -- Ward


@enduml