@startuml ClassDiagram

skin rose
scale 2
hide circle

class Album {
    - id: Long
    - name: String
    - description: String
    - placeId : String
    - placeLongtitude: double
    - placeLatitude: double
    - placeName: String
    - placeCoverImageUrl: String
    - albumImages: List<AlbumImage>
    - userId: Long
}

class AlbumImage {
    - id: Long
    - imageUrl: String
    - imagePublicId: String
    - albumId: Long
}

class BaseUser {
    # id: Long
    # role: UserRole
    # email: String
    # password: String
    # firstName: String
    # lastName: String
    # isVerified: boolean
}

class Admin {

}

class User {
    - avatarUrl: String
    - avatarPublicId: String
    - dateOfBirth: Date
    - gender: String
    - phoneNumber: String
    - point: int
    - isCreatedProfile: boolean
    - favoritePlaces: List<FavouritePlace>
    - trips: List<Trip>
    - albums: List<Album>
}

class Place {
    - id: Long
    - longitude: double
    - latitude: double
    - address: String
    - name: String
    - iconUrl: String
    - iconPublicId: String
    - coverImageUrl: String
    - coverImagePublicId: String
    - description: List<Section>
    - checkInPoint: int
    - checkInRange: float
    - category: PlaceCategory
    - timeOpen: LocalTime
    - timeClose: LocalTime
    - alternativeName: String
    - operator: String
    - link: String
    - placeImages: List<PlaceImage>
    - feedbacks: List<Feedback>
}

class PlaceImage {
    - id: Long
    - imageUrl: String
    - imagePublicId: String
    - placeId: Long
}

class Feedback {
    - id: Long
    - userName: String
    - userAvatar: String
    - rating: float
    - comment: String
    - feedbackImages: List<FeedbackImage>
    - time: Date
    - placeId: Long
}

class FeedbackImage {
    - id: Long
    - imageUrl: String
    - imagePublicId: String
    - feedbackId: Long
}

class Section {
    - id: Long
    - title: String
    - content: String
    - imageUrl: String
    - imagePublicId: String
    - placeId: Long
}

class FavouritePlace {
    - id: Long
    - placeId: Long
    - userId: Long
    - placeLongtitude: double
    - placeLatitude: double
    - placeName: String
    - placeCoverImageUrl: String
}

class Trip {
    - id: Long
    - name: String
    - imageUrl: String
    - imagePublicId: String
    - startTime: Date
    - endTime: Date
    - tripPlaces: List<TripPlace>
    - userId: Long
}

class TripPlace {
    - id: Long
    - placeLongtitude: double
    - placeLatitude: double
    - placeName: String
    - placeCoverImageUrl: String
    - startTime: Date
    - endTime: Date
    - tripId: Long
}

enum UserRole {
    ADMIN
    USER
}

enum PlaceCategory {
    HOTEL
    RESTAURANT
    MUSEUM
    PARK
    SHOPPING
    ENTERTAINMENT
    OTHER
}

class RefreshToken {
    - id: Long
    - token: String
    - email: String
}

BaseUser <|-right- Admin
BaseUser <|-down- User
Place -left- Feedback
Feedback -down- FeedbackImage
User -down- Trip
User -left- FavouritePlace
Trip -left- TripPlace
User -right- Album
Album -down- AlbumImage
Place -up- Section
Place -down- PlaceImage

@enduml