@startuml ClassDiagram

skin rose
scale 2

class AdministrativeRegion {
    id: Integer
    name: String
    nameEn: String
    codeName: String
    codeNameEn: String

}

class AdministrativeUnit {
    id: Integer
    fullName: String
    fullNameEn: String
    shortName: String
    shortNameEn: String
    codeName: String
    codeNameEn: String
}

class Province {
    - code: String
    - name: String
    - nameEn: String
    - fullName: String
    - fullNameEn: String
    - codeName: String
    - regionId: Long
    - unitId: Long
}

class District {
    - code: String
    - name: String
    - nameEn: String
    - fullName: String
    - fullNameEn: String
    - codeName: String
    - unitId: Long
    - provinceCode: String
}

class Ward {
    - code: String
    - name: String
    - nameEn: String
    - fullName: String
    - fullNameEn: String
    - codeName: String
    - unitId: Long
    - districtCode: String
}

class ProvinceDetail {
    - provinceCode: String
    - longitude: double
    - latitude: double
    - area_km2: double
    - description: String
    - bestTimeToVisit: String
    - festivals: String
    - localTransport: String
    - localFood: String
    - howToGetThere: String
}

class Address {
    - id: Long
    - province: Province
    - district: District
    - ward: Ward
    - street: String
    - targetType: AddressTargetType
    - targetId: Long
}

enum AddressTargetType {
    USER,
    PLACE,
}

class Image {
    - id: Long
    - imageUrl: String
    - imagePublicId: String
    - targetType: ImageType
    - targetId: Long
}

enum ImageTargetType {
    ALBUM,
    PLACE_IMAGE,
    CATEGORY_ICON,
    PLACE_COVER,
    FEEDBACK,
    POST,
    USER_AVATAR,
    SECTION,
}

class Album {
    - id: Long
    - name: String
    - description: String
    - createAt: LocalTime
    - updatedAt: LocalTime
    - place: Place
    - userId: Long
}

class Account {
    - id: Long
    - role: UserRole
    - email: String
    - password: String
    - isVerified: boolean
    - isActive: boolean
    - isDeleted: boolean
    - createdAt: LocalTime
}

class RefreshToken {
    - id: Long
    - token: String
    - accountId: Long
}

class User {
    - id: Long
    - firstName: String
    - lastName: String
    - isCreatedProfile: boolean
    - avatarImage: Image
    - dateOfBirth: Date
    - gender: String
    - phoneNumber: String
    - point: int
    - address: Address
    - accountId: Long
    - createAt: LocalTime
}

enum UserRole {
    ADMIN
    USER
}

class CheckIn {
    - id: Long
    - userId: Long
    - place: Place
    - checkInTime: LocalTime
}

class FavouritePlace {
    - id: Long
    - placeId: Long
    - userId: Long
}

class Place {
    - id: Long
    - longitude: double
    - latitude: double
    - address: Address
    - name: String
    - category: PlaceCategory
    - coverImage: Image
    - rating: float
    - totalRating: int
    - totalFeedback: int
}

class PlaceDetail {
    - id: Long
    - placeId: Long
    - description: String
    - checkInPoint: int
    - checkInRangeMeter: float
    - timeOpen: LocalTime
    - timeClose: LocalTime
    - isClosed: boolean
    - bestTimeToVisit: String
    - priceRangeTop: int
    - priceRangeBottom: int
    - isVerified: boolean
    - alternativeName: String
    - operator: String
    - url: String
}

class Feedback {
    - id: Long
    - placeId: Long
    - user: User
    - rating: float
    - content: String
    - createAt: LocalTime
    - updateAt: LocalTime
}

class Section {
    - id: Long
    - title: String
    - content: String
    - image: Image
    - placeDetailId: Long
}

class PlaceCategory {
    - id: Integer
    - name: String
    - nameEn: String
    - iconImage: Image
}

class Trip {
    - id: Long
    - name: String
    - startTime: Date
    - endTime: Date
    - userId: Long
    - listTripPlaces: List<TripPlace>
}

class TripPlace {
    - id: Long
    - place: Place
    - tripId: Long
    - startTime: Date
    - endTime: Date
    - placeNote: String
}

class Post {
    - id: Long
    - user: User
    - content: String
    - createAt: LocalTime
    - updateAt: LocalTime
    - place: Place
    - isTripShare: boolean
    - trip: Trip
    - like: int
}

class Comment {
    - id: Long
    - user: User
    - content: String
    - createAt: LocalTime
    - updateAt: LocalTime
    - postId: Long
    - parentId: Long
    - like: int
}

class Like {
    - id: Long
    - user: User
    - targetId: Long
    - targetType: LikeTargetType
}

enum LikeTargetType {
    POST,
    COMMENT,
}

User -up- Trip
User -up- Album
User -up- FavouritePlace
User -down- RefreshToken
User -right- Post
User -right- Comment
User -up- CheckIn
User -down- Like
User -left- UserRole
User -down- Account

Trip -up- TripPlace

Place -down- Feedback
Place -up- PlaceDetail
Place -up- PlaceCategory
Place -down- FavouritePlace
Place -down- CheckIn
Place -down- TripPlace
Place -down- Album
Place -down- Post

PlaceDetail -right- Section

Feedback -down- User

Province -up- AdministrativeUnit
Province -up- AdministrativeRegion
Province -left- ProvinceDetail

District -up- AdministrativeUnit
District -left- Province

Ward -up- AdministrativeUnit
Ward -left- District

Post -down- Comment
Post -up- Trip

Address -up- Province
Address -up- District
Address -up- Ward
Address -down- AddressTargetType

Image -up- ImageTargetType

Like -up- LikeTargetType

@enduml